id = "kde-breeze-dark-theme"
name = "KDE Breeze Dark Theme"
version = "0.1.0"
schema_version = 1
authors = ["kde-community", "jovi-j"]
description = "KDE's Breeze dark theme for Zed."
repository = "https://github.com/jovi-j/kde-breeze-dark-zed"
